# Generated by Django 3.2.6 on 2021-11-18 11:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_boat_boat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='boat_image',
            field=models.ImageField(blank=True, default='images/no_image.jpg', null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2021, 11, 18))),
                ('end_date', models.DateField(default=datetime.date(2021, 11, 19))),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.boat')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
